name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive # 自动递归处理子模块

    - name: Install deps
      # 习惯性加上 -y 以防安装过程中弹出交互确认导致卡死
      run: sudo apt-get update && sudo apt-get install -y libgtest-dev zlib1g-dev libboost-all-dev

    - name: Configure CMake
      # -B 会自动创建目录，不需要手动 mkdir
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # 直接指定 build 目录进行构建，无需 cd 切换路径
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}